### ISSUE TITLE
Allow not implemented schools

### ISSUE THREAD

**Issue by SachsenspieltCoding** [ArtrenH/VPlan_FR#220]
Since I was asked to contribute, here I am.
IMO it would be a good option to let the user add their own school with their student credentials. Maybe this could be some kind of experimental feature that warns the user: it can get buggy if you use untested schools.

**Comment by ArtrenH** [comment]
Actually, this is implemented. Students can submit schools that get sent to us for review for safety reasons

**Comment by SachsenspieltCoding** [comment]
But why do they need to be reviewed? I don't get it.

**Comment by ArtrenH** [comment]
In theory, schools hosted on stundenplan24.de don't need to be verified but because we need to restart our plan loader, this is our current way. We plan to automatically restart it after adding a school to the database.
We already do check if a submitted school is valid and the credentials are correct.

**Comment by SachsenspieltCoding** [comment]
I totally understand. But from the user's point of view, it's a bit ugly to have to contact the developers to use a replacement schedule application.
